data:
  ticker: "^GSPC"
  start: "2010-01-01" # start of training set
  end: "2023-01-01"   # end of evaluation set
  split_date: "2019-01-01"

features:
 - 'Vol20/VIX'
 - 'Vol5/VIX'
 - 'Scaled_Lag_1d'
 - 'Scaled_Lag_3d'
 - 'Sharpe-like_10'
 - 'Sharpe-like_5'
 - 'log_returns_zscore'
 - 'VIX_zscore'
 - 'Momentum5_20'
 - 'Momentum10_20'
 - 'Momentum5_10'
 - 'Momentum3_20'
 - 'Momentum3_10'
 - 'Momentum3_5'
 - 'Scaled_weighted_avg'

features:
 - 'VOL5/VIX'
 - 'VOL20/VIX'
 - 'lag_return_1/vol20'
 - 'lag_return_2/vol20'
 - 'lag_return_3/vol20'
 - 'Sharpe-like_10/20'
 - 'Sharpe-like_5/20'
 - 'log_returns_z_20'
 - 'VIX_z_20'
 - 'Momentumn3_5'
 - 'Momentumn3_10'
 - 'Momentumn3_20'
 - 'Momentumn5_10'
 - 'Momentumn5_20'
 - 'Momentumn10_20'
 - 'EWLR_0.8_1-20/20'

training:
  model: "lgbm"         # rf, xgb, or lgbm
  n_optuna_trials: 20
  top_n_models: 5

evaluation:
  model_names:
   - "lgbm_trial_1"
   - "lgbm_trial_2"
   - "lgbm_trial_3"
   - "lgbm_trial_4"
   - "lgbm_trial_5"
  eval_tickers:
   - "^GSPC"
   - "^IXIC"
   - "^GDAXI"
  pdf_report_name: "lgbm_report.pdf"